version: "3"
services:
   etcd0:
      image: quay.io/coreos/etcd:v2.3.8
      hostname: etcd0
      networks:
         - cluster
      ports:
         - 2379:2379
      volumes:
         - "/home/lucho/00/docker/etcd/certs:/etc/ssl/certs"
      command: -name etcd0 -advertise-client-urls http://etcd0:2379,http://etcd0:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls http://etcd0:2380  -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster-1 -initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380 -initial-cluster-state new
   etcd1:
      image: quay.io/coreos/etcd:v2.3.8
      hostname: etcd1
      networks:
         - cluster
      volumes:
         - "/home/lucho/00/docker/etcd/certs:/etc/ssl/certs"
      command: -name etcd1 -advertise-client-urls http://etcd1:2379,http://etcd1:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls http://etcd1:2380  -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster-1 -initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380 -initial-cluster-state new
networks:
  cluster:
# alias ctl=" docker run --rm --network etcd_cluster cburki/etcdctl:latest"
