version: "3"
services:
  nfs:
    image: fuzzle/docker-nfs-server:latest
    restart: always
    privileged: true
    environment:
      - NFS_EXPORT_DIR_1=/data/k8s
      - NFS_EXPORT_DOMAIN_1=*
      - NFS_EXPORT_OPTIONS_1=rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure
    volumes:
      - ./data/:/data
    ports:
      - 111:111
      - 111:111/udp
      - 2049:2049
      - 2049:2049/udp
      - 32765:32765
      - 32765:32765/udp
      - 32766:32766
      - 32766:32766/udp
      - 32767:32767
      - 32767:32767/udp
