## STATIC CONFIGURATION
log:
    level: INFO
  
  api:
    insecure: true
    dashboard: true
  
  entryPoints:
    web:
      address: ":80"
    websecure:
      address: ":443"
      
  providers:
    docker:
      endpoint: "unix:///var/run/docker.sock"
      exposedByDefault: false
  
  ##---DNS CHALLENGE---##
  #certificatesResolvers:
    #lets-encr:
      #acme:
        #email: luchito123@yopmail.com
        #storage: acme.json
        #dnsChallenge:
          #resolvers:
  
  ##---HTTP CHALLENGE--##
  certificatesResolvers:
    lets-encr:
      acme:
        storage: acme.json
        email: [email]
        httpChallenge:
          entryPoint: web