version: '3'

services:
  db:
    container_name: wp-mysql
    image: mysql:5.7
    volumes:
       - $PWD/data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: [PASS ROOT]
       MYSQL_DATABASE: [NAME DATABASE]
       MYSQL_USER: [USER DATABASE]
       MYSQL_PASSWORD: [PASS DATABASE]
    ports:
      - "3306:3306"
    networks:
      - my_net

  wp:
    container_name: wp-web
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: [HOST DATABASE]
      WORDPRESS_DB_USER: [USER DATABASE]
      WORDPRESS_DB_PASSWORD: [PASS DATABASE]
    networks:
      - my_net
networks:
  my_net:
